version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qrAdmin
      POSTGRES_DB: QrAsistencia
    ports:
      - 5433:5432